### ISSUE TITLE
Scrollview not working

### ISSUE THREAD

**Issue by Type1J** [ianharrigan/haxeui#201]
I tried this:

    package;

    import haxe.ui.toolkit.core.Toolkit;
    import haxe.ui.toolkit.controls.Button;
    import haxe.ui.toolkit.core.Macros;
    import haxe.ui.toolkit.core.Root;
    import haxe.ui.toolkit.themes.GradientTheme;
    import haxe.ui.toolkit.containers.VBox;
    import haxe.ui.toolkit.containers.ScrollView;

    class Main {
        public static function main() {
            Toolkit.theme = new GradientTheme();
            Toolkit.init();
 
            Toolkit.openPopup({width: 370, height: 270}, function(root:Root) {
                var button:Button = new Button();
                button.text = "Root 1";
                button.x = 10;
                button.y = 10;
                root.addChild(button);
            });
 
            Toolkit.openPopup({y: 310, width: 370, height: 270}, function(root:Root) {
                var button:Button = new Button();
                button.text = "Root 2";
                button.x = 10;
                button.y = 10;
                root.addChild(button);
            });
         
            Toolkit.openPopup({x: 410, width: 370, height: 560}, function(root:Root) {
                var view = new ScrollView();
                view.x = 10;
                view.y = 10;
                view.width = 350;
                view.height = 200;
                root.addChild(view);

                var newButton = function(i:Int) {
                    var button = new Button();
                    button.text = 'Root 3 $i';
                    return button;
                }
                for (i in 0...30) {
                    view.addChild(newButton(i));
                }
            });
        }
    }
For the ScrollView, the buttons generated here don't get clipped, and no scrollbar appears.

**Comment by ianharrigan** [comment]
Ok, i can see what is happening here. Basically, the scrollview needs a single child that it will use for the scroll content, so in your example, it thinks the scrollable content is the first single button, so this code works fine:

Using vbox:
```haxe
Toolkit.open(function(root:Root) {
    var view = new ScrollView();
    view.x = 10;
    view.y = 10;
    view.width = 350;
    view.height = 200;
    var vbox:VBox = new VBox();
    view.addChild(vbox);
    root.addChild(view);

    var newButton = function(i:Int) {
        var button = new Button();
        button.text = 'Root 3 $i';
        return button;
    }

    for (i in 0...30) {
        vbox.addChild(newButton(i));
    }
});
```

Using hbox:
```haxe
Toolkit.open(function(root:Root) {
    var view = new ScrollView();
    view.x = 10;
    view.y = 10;
    view.width = 350;
    view.height = 200;
    var hbox:HBox = new HBox();
    view.addChild(hbox);
    root.addChild(view);

    var newButton = function(i:Int) {
        var button = new Button();
        button.text = 'Root 3 $i';
        return button;
    }

    for (i in 0...30) {
        hbox.addChild(newButton(i));
    }
});
```

Using grid:
```haxe
Toolkit.open(function(root:Root) {
    var view = new ScrollView();
    view.x = 10;
    view.y = 10;
    view.width = 350;
    view.height = 200;
    var grid:Grid = new Grid();
    grid.columns = 3;
    view.addChild(grid);
    root.addChild(view);

    var newButton = function(i:Int) {
        var button = new Button();
        button.text = 'Root 3 $i';
        return button;
    }

    for (i in 0...30) {
        grid.addChild(newButton(i));
    }
});
```

So that should all work fine after you add a a "content" component (can be anything). 

However, all that said and done, i think this should be made a little better/clearer, ill leave this open while i have a think about it.

Cheers,
Ian

**Comment by ianharrigan** [comment]
![grid_scroll](https://cloud.githubusercontent.com/assets/3024242/5598039/e305002c-92ae-11e4-944e-ef0993ac8b06.jpg)

**Comment by Type1J** [comment]
I see. I got it to work, now. Thanks! If you were thinking about how to change the API to make it cleaner, then I would say that addChild() should throw on the second element added with an explanation of how the scroll view should only have one child.

**Comment by ianharrigan** [comment]
Ok, yeah, i was thinking about how best to achieve that, i think maybe it might be better to just trace a warning though rather than have the whole program die. What do you think?

"WARNING: ScrollView will only use the first child as the scroll content"

?

Cheers,
Ian

**Comment by Type1J** [comment]
Yeah, I suppose that's much more friendly.
