### ISSUE TITLE
Is it possible to create a standalone EXE file for Windows?

### ISSUE THREAD

**Issue by ShedoSurashu** [ianharrigan/haxeui#202]
I tried building via C++ and it seems to store the resources (XML UIs, CSS, etc) outside of the executable file. How can I contain the folders **assets**, **fonts** and **styles** into the main executable?

Also an additional question, how do I define the values for these fields? I've defined the `title`, `version`, and `company` sections on the application.xml's `<meta` tag but they don't seem to reflect here after I compiled it.
![20150103160003327](https://cloud.githubusercontent.com/assets/635367/5602857/aebd613c-93a4-11e4-9fc5-8b2370db1089.png)

**Comment by ianharrigan** [comment]
Hi,

Yes, there was a method to allow this, basically, by adding "embed=true" in all the <assets/> tags in both your project and in the include.xml file. 

I had some <haxedef>'s that would have allowed this, however, it seemed that this crashed a linux build, so i removed it (temporarily). Ill bump this up the list as its certainly something i would want for future apps.

Ill let you know when i figure something out.

As for the second question, im not sure at all to be honest, might make sense to ask in in the openfl places.

Cheers,
Ian

**Comment by ShedoSurashu** [comment]
Ah awesome, I'll look forward to that. It's good to know that it's coming. And as for the application meta data bit, it's not high on my list right now so I'll probably get back to finding more info about it when I finally come to the later points of developing my project.

**Comment by Type1J** [comment]
@ShedoSurashu I don't know the answer to your second question right now, but to help you with your question to OpenFL build tools: You specify those in a resource file (*.rc) in C++ projects, and I don't know if your project.xml will generate or let you include such a file.

The rest of this post could be complete garbage, but I thought it might be helpful to give you a loose-ended, unchecked start of a solution:

If you ask, and they say that project.xml doesn't support windows resource files, then you still should be able to do it in a more direct, but less clean, way: put the following in one of your *.hx files before the class that it defines:

    #if windows #if cpp
    @:buildXml('
    <files id="haxe">
      <file name="../../../../file.rc" />
    </files>
    ')
    #end #end

The xml part is totally a guess, and I haven't checked anything out to see if it works :-) (you may have to play with the number of "../", and there may be a way to remove the need for them, but I don't know it.) This block is also what you would do if you wanted to add a *.cpp file to your OpenFL project that builds at the same time as your Haxe code:

    #if cpp
    @:buildXml('
    <files id="haxe">
      <file name="../../../../cpp_src/file.cpp" />
    </files>
    ')
    #end

I hope that helps.

**Comment by ianharrigan** [comment]
Its actually a lot simpler that that :)... Take HaxeUI's application.xml, if you add the "embed" attribute to all the resources then they will be compiled into the final .exe, eg:

```xml
<?xml version="1.0" encoding="utf-8"?>
<project>
	<haxelib name="openfl" />
	<haxelib name="actuate" />
	<assets path="assets" rename="assets" embed="true" />
	<assets path="assets/styles" rename="styles" embed="true" />
	<assets path="assets/fonts" rename="fonts" embed="true" />
</project>
```
However, the problem with this was that it for some reason crashed the build on linux. I dont have a linux box, but im guess i could try and with a VM or find someone who does.

Cheers,
Ian

**Comment by ianharrigan** [comment]
Heres the related issue: https://github.com/ianharrigan/haxeui/issues/167

**Comment by ianharrigan** [comment]
Ok, so i thanks that should work now. If you put:

```xml
<set name="haxeui-embed-resources" />
```
before
```xml
<haxelib name="haxeui" />
```
Then haxeui specific resources should end up compiled into the final .exe. If you want your own resources also compiled in then you can do something like this:
```xml
<!-- normal resources, external to final output -->
<section unless="haxeui-embed-resources">
   <assets path="assets" rename="assets" embed="false" />
   <assets path="assets/css" rename="css" embed="false" />
   <assets path="assets/ui" rename="ui" embed="false" />
</section>
<!-- embedded resources, inside final output -->
<section if="haxeui-embed-resources">
   <assets path="assets" rename="assets" embed="true" />
   <assets path="assets/css" rename="css" embed="true" />
   <assets path="assets/ui" rename="ui" embed="true" />
</section>
```
There are a few other build options, described into the updated FlashDevelop template: https://github.com/ianharrigan/haxeui/blob/master/templates/flash-develop/%24%28BaseDir%29/Projects/600%20HaxeUI%20-%20HaxeUI%20Project/application.xml.template

Once you get a chance, can you let me know if that works so i can close the related issue?

Cheers,
Ian

**Comment by Type1J** [comment]
@ianharrigan Sorry :-), it's 2 different kinds of "resources" that we're talking about. I was only suggesting the method that I described above for the "title", "version", and "company" strings that are stored in Windows .exe file, but no other targets.

I wasn't suggesting using the .rc file for anything else because it isn't portable (Windows only), and it's really hard to use in Haxe if you wanted to use it inside your app. It's only useful to make Windows Explorer show you the right properties for the .exe if you ask it.

**Comment by ianharrigan** [comment]
Ah ha! Right, gotcha, sorry, my misunderstanding. :)

Well, ive added the ability to pack all haxeui resources into the final exe now, so thats a good thing anyway!

Cheers,
Ian

**Comment by ianharrigan** [comment]
Also, for the meta data, one solution might be: http://www.7tutorials.com/how-change-metadata-stored-executable-files.

Not sure if it has a cmd line interface, but if it did it could be automated.

**Comment by ShedoSurashu** [comment]
@Type1J Where do I get the `.rc` file?

@ianharrigan Just updated haxeui right now and embedding works perfectly! Thanks! :D Is there a way to go the extra mile and just add all the resources into the EXE? (E.g. lime.ndll, std.dll, etc)

**Comment by ianharrigan** [comment]
@ShedoSurashu, there is apparently static linking available in openfl next, but they arent supplying the .libs yet. As far as i know you would have to build openfl from source yourself and statically link the .lib files, which is doable, but personally, ill wait till ill see how the build process of openfl evolves. 

That said, once it becomes "standard" ill certainly be using it. The end goal, without doubt, is to have the ability to have a single .exe with everything in it.

Cheers,
Ian

**Comment by ShedoSurashu** [comment]
@ianharrigan neat! By the way, I attempted hacking the resource of the EXE as per your suggestion but it shows up empty on ResHacker for some reason so I'm waiting on @Type1J's solution as it seems to be the more convenient way to go about it.

**Comment by Type1J** [comment]
Here's a template. Replace the @SOME_VAR_NAME@ with your values:

    1 VERSIONINFO
      FILEVERSION    @ARG_VERSION_MAJOR@,@ARG_VERSION_MINOR@,@ARG_VERSION_PATCH@,@ARG_VERSION_TWEAK@
      PRODUCTVERSION     @ARG_VERSION_MAJOR@,@ARG_VERSION_MINOR@,@ARG_VERSION_PATCH@,@ARG_VERSION_TWEAK@
    #ifdef _DEBUG
      FILEFLAGS 0x1L
    #else
      FILEFLAGS 0x0L
    #endif
    BEGIN
      BLOCK "StringFileInfo"
      BEGIN
        BLOCK "040904E4"
        BEGIN
          VALUE "CompanyName", "@ARG_VENDOR@"
          VALUE "FileDescription", "@ARG_DESCRIPTION@"
          VALUE "FileVersion",     "@ARG_VERSION_MAJOR@.@ARG_VERSION_MINOR@.@ARG_VERSION_PATCH@.@ARG_VERSION_TWEAK@"
          VALUE "ProductName", "@ARG_NAME@"
          VALUE "ProductVersion",     "@ARG_VERSION_MAJOR@.@ARG_VERSION_MINOR@.@ARG_VERSION_PATCH@.@ARG_VERSION_TWEAK@"
        END
      END

      BLOCK "VarFileInfo"
      BEGIN
        VALUE "Translation", 0x409, 1252
      END
    END

I use this .rc file template in the build system for a C++ app that I made, but I honestly don't remember what some of these statements do, so you may want to look them up on MSDN.

**Comment by Type1J** [comment]
@ShedoSurashu For adding the ndlls to your exe, you want "static linking", but be careful here. There isn't a technical problem doing the static linking, and on iOS it's required. It's just a line in your project.xml I think.

However, I said "be careful here" because while there may be no technical problem, there may be a legal problem. The "lime.ndll" file contains OpenAL on Windows, and a few other platforms where it's not normally installed by the OS (iOS has OpenAL as a dylib already, so it's not included in "lime.ndll" on iOS). OpenAL is LGPL code, which legally requires you to either only dynamically link to it, or release your code under the LGPL licence as well.

If your project is already open source, and under LGPL, then that may not be a problem.
