### ISSUE TITLE
HaxeUI defaults to use yagp, but doesn't include it in haxelib.json "dependencies" list.

### ISSUE THREAD

**Issue by Type1J** [ianharrigan/haxeui#205]
In order to compile any app with HaxeUI 1.6.16, you must have yagp installed manually, or

    <set name="haxeui-no-gif-support" />

in the project.xml file because "haxelib.json" doesn't include yagp in the "dependencies" list.

**Comment by ianharrigan** [comment]
And if you dont have yagp installed what error are you getting?

**Comment by Type1J** [comment]
I get

    Error: Could not find haxelib "yagp", does it need to be installed?

I believe that this library should either not be used by default (in other words, require someone to use "haxeui-gif-support" instead of "haxeui-no-gif-support"), or if it _is_ used by default, then it should be in the list of dependencies, so it will be installed when HaxeUI is installed.

That's only opinion, of course. It would be least surprising to have no problems to fix after a fresh install.

**Comment by ianharrigan** [comment]
I think it probably makes sense, as you said, to have it in the dependencies section, i mean then it should be fine and if you choose haxeui-no-gif-support then it wont be part of the project. As you said, makes sense so there is no gotchas when you first haxelib it
