### ISSUE TITLE
Gradient Theme not properly embedded in 1.6.16

### ISSUE THREAD

**Issue by Type1J** [ianharrigan/haxeui#206]
When using HaxeUI 1.6.14, everything works as expected, but when using 1.6.16 (on flash target) I get

    Assets.hx:469: [Assets] String asset "styles/gradient/gradient.css" exists, but only asynchronously

, and the components on screen are drawn with no theme. This problem occurs after this call:

    Toolkit.theme = new GradientTheme();

The native target seems to work as expected, so only flash is known to be affected.

**Comment by ianharrigan** [comment]
Never seen that before! Is this something related to embedding the resources?

**Comment by Type1J** [comment]
I added

      <set name="haxeui-embed-resources" />

to the project.xml, and that didn't change anything. I'm using Flash Player 15 as installed from FlashDevelop.

**Comment by ianharrigan** [comment]
Hmmmm, very bizarre... I can reproduce it however which is a good thing!

**Comment by ianharrigan** [comment]
Can you try that with 1.6.17 (latest haxelib version)?

**Comment by Type1J** [comment]
Yep, it works fine now in flash and native. :-) Thanks!
