### ISSUE TITLE
Expose Event.CHANGE of TextInput's textfield

### ISSUE THREAD

**Issue by Beeblerox** [ianharrigan/haxeui#207]
i'm adding it with reflection currently:
```
public static function getTextFieldForTextInput(input:TextInput):TextField
{
	var textDisplay = Reflect.field(input, "_textDisplay");
	return cast(Reflect.field(textDisplay, "_tf"), TextField);
}
```
and then add event listener to it

**Comment by ianharrigan** [comment]
Does:

```haxe
textField.onChange = function(e) {
}
```
Not work?
Or:
```haxe
textField.addEventListener(UIEvent.CHANGE, ...):
```
Or:
```haxe
textField.addEventListener(Event.CHANGE, ...)
```
They should work, but ive just got back from being away so havent tested, but im fairly sure that ive tested this prevously.

Either way, leave it with me and ill see if there is a bug

Cheers,
Ian

PS: ill have to check the API, but i think you can get the `TextField` with `TextInput.display`, but it may not be public, ill check that also.

**Comment by Beeblerox** [comment]
@ianharrigan Setting `onChange` helped me. Sorry about this.
