### ISSUE TITLE
Changing TextInput.disabled from true to false doesn't changes color of the text.

### ISSUE THREAD

**Issue by Beeblerox** [ianharrigan/haxeui#208]
It changes color of text component background though.

**Comment by Beeblerox** [comment]
ok, i found the problem: i'm using gradient theme and in `gradient.css` which `TextInput` block doesn't have `color` value, but `TextInput:disabled` does. So you need only to add `color:0x000000;` to resolve it.

**Comment by ianharrigan** [comment]
Right, gotcha... Good catch... Cheers!

Ill fix it when i get a moment.

Thanks again!
Ian
