### ISSUE TITLE
Low performance on android (long text) 

### ISSUE THREAD

**Issue by marcelofrau** [ianharrigan/haxeui#215]
Hello,

I wanted to know if the performance is severely degradated with a long text. I have run some tests and on android the low performance make my application unusable. Can you tell if I'm doing something wrong?

Someone already experienced this? How can it be solved?
Thanks!

```
    public static function main():Void {      
              
            Toolkit.init();  
            Toolkit.openFullscreen(function(root:Root) {  
                  
                var text = new Text();  
                  
                text.text = "really long text here";  
                      
                text.width = root.width - 50;  
                text.wrapLines = true;  
                text.style.color = 0x000000;  
                text.style.backgroundColor = 0xFFFFFF;  
                var scroll = new ScrollView();  
                scroll.style.backgroundColor = 0xFFFFFF;  
                scroll.addChild(text);  
                  
                scroll.height = root.height;  
                scroll.width = root.width;  
                  
                root.style.backgroundColor = 0xFFFFFF;  
                  
                root.addChild(scroll);  
                  
            });  
        }  
```

See an example:
http://pastebin.com/NqL67sMd

Another example:
http://pastebin.com/btU0dsmz

I have made a second example, and I confirmed the issue is purely related with the scrollview Widget. Just tested with ListView and it runs very smooth in this same device.

**Comment by marcelofrau** [comment]
I have made a test without the wrapLines (setting it to false) and the problem still occur.
Perhaps changing the font will solve?

**Comment by marcelofrau** [comment]
Maybe I'm wrong, but I think the problem is related to the font/text renderer. I have looked into the ScrollView.hx source and didn't find anything that can cause a performance problem. 

I was testing on a Galaxy Ace 3 mobile phone. It has a dual core 1ghz CPU, it's strange because I have another projects using this mobile and haxe and doesn't notice this performance problem at all. (I am using HaxeFlixel on othe projects)

If you can direct me where the performance issue can be, I can take a look on the source and try to change and send a patch to you (If there is anything I can do)

Please respond @ianharrigan  :)

**Comment by ianharrigan** [comment]
Sorry Marcel,

I was out of action for the weekend. Ill look into, what theme are you using? Have tried using a default (system) font?

Cheers,
Ian

**Comment by marcelofrau** [comment]
Hello, 

No problem, thanks for the response. I have tryied with two themes, the GradientMobileTheme and the GradientTheme. Apparently this does not happends only with long text, the ScrollView component is slow always, event if it has just some buttons. 

If I use another component with scroll, it works normally. I've tried to investigate further but didn't find anything. Please check. 

I've made a test to isolate the problems, I was suspecting that maybe there was something with the Layouts, I've tryied to change the layout to AbsoluteLayout and even in this way the scroll is performing slow on android.

This only happens on android, on every other platform (not tested iOS), the performance is great.
I've tryied to change the font, to let the default one, but the low performance is the same.

This is my last test: 
´´´
public static function main():Void {	
		
		Toolkit.theme = new GradientMobileTheme();
		Toolkit.init();
		Toolkit.openFullscreen(function(root:Root) {
			var b:Button = new Button();
			b.text = "Test button";
			b.x = 10;
			b.y = 10;
			root.addChild(b);
			
			var list = new ListView();
			list.x = 10;
			list.y = 60;
			
			list.inertialScrolling = true;
			list.width = root.width - 20;
			list.height = root.height - 70;
			
			for (i in 0...100) {
				list.dataSource.add( { text: 'Foo bar $i' } );
			}
			
			var scrollView = new ScrollView();
			//scrollView.inertialScrolling = true;
			//scrollView.virtualScrolling = true;
			
			scrollView.width = root.width - 20;
			scrollView.height = root.height - 70;
			
			scrollView.x = 10;
			scrollView.y = 60;
			
			var vertical = new Container();
			
			/*
			vertical.height = 1800;
			vertical.width = root.width;
			*/
			vertical.layout = new AbsoluteLayout();
			//vertical.style.spacing = 50;
			
			
			var incy = 0;
			for (i in 0...20) {
				var bt = new Button();
				bt.text = 'Button xxxxxxxxxxxxx $i';
				
				bt.height = 10;
				
				bt.x = 2;
				bt.y = incy;
				
				trace(incy);
				incy += 90;
				
				vertical.addChild(bt);
			}
			
			vertical.height = incy;
			vertical.autoSize = true;
			
			scrollView.addChild(vertical);
			
			
			scrollView.visible = true;
			list.visible = !scrollView.visible;
			b.onClick = function(event) {
				b.text = 'Clicked ${Lib.getTimer()}';
				
				list.visible = !list.visible;
				scrollView.visible = !scrollView.visible;
				
			};
			
			
			root.addChild(list);
			root.addChild(scrollView);
	});
}

´´´


Also, thanks for this great API, you have make a possibility to me to use haxe in my work. Please, tell me that this can be fixed :) 

If you have low time, I can check where something can be wrong. Today tonight (GMT+3) I'll make some more tests to send to you, and let you know if I find something out.

If you want I can send you the entire project so you can check the source for yourself.

Thanks in advance.
Best regards.

**Comment by ianharrigan** [comment]
I think that should be fine for now... Ill check it out and see, at least see if i can reproduce it... 

Ill keep you posted.

Cheers,
Ian

**Comment by marcelofrau** [comment]
Hello, 
I've just tested with the haxeui from git, I need to checkout to some branch to test the change you made?

I think is a little better, but is still slow, very different from the performance from the ListView widget.
In the last test I shared here you can see both tests, with listview and scrollview. 

Thanks,

**Comment by ianharrigan** [comment]
So list view is fine? What about turning off intertial scrolling? What about listviews with loads of subtext (to make them wrap)

**Comment by marcelofrau** [comment]
The list view as far I have tested is running very smooth and fast even with intertialScrolling. The scrollview with or without the inertialscrolling is with a compromised performance. I'll try to enrich the items in the list view with a lot more text to see if the performance degradate and let you know.. 

If you want I can send you a video showing the performance on all platforms.

I don't know if there is something to do with the wrap lines, because even if I create a scroll view with buttons with just single line text, the performance is also degradated.

I'll make some more tests with the listview so we can isolate the problem on scrollview or not.

Thanks again..

**Comment by marcelofrau** [comment]
I have made a test with a listview with really long texts, and still run perfectly fine. 
And tested a ScrollView with a lot of empty buttons and the performance is very very slow.
If I change all the buttons in the scrollview to Container (just to have a box inside the scrollview), all goes perfectly fine.

This code, runs slow with Buttons on ScrollView
´´´
public static function main():Void {	
		
	Toolkit.theme = new GradientMobileTheme();
	Toolkit.init();
	Toolkit.openFullscreen(function(root:Root) {
		var b:Button = new Button();
		b.text = "Test button";
		b.x = 10;
		b.y = 10;
		root.addChild(b);
		
		var quit:Button = new Button();
		quit.text = 'Quit';
		quit.x = root.width - 90;
		quit.y = 10;
		quit.onClick = function(e) {
			System.exit(0);
		}
		
		root.addChild(quit);
		
		var list = new ListView();
		list.x = 10;
		list.y = 60;
		
		list.inertialScrolling = true;
		list.width = root.width - 20;
		list.height = root.height - 70;
		
		for (i in 0...100) {
			list.dataSource.add( { text: 'Foo bar with a really really really \n long text to provoke a wrap line to check if it will perform slow on android \n wrap lines is not automatically in this one, so I\'m forcring a break \n and seeing if the performance is slower even with this long text that doesnt describe anything.. this is just to test the performance $i' } );
		}
			
		var scrollView = new ScrollView();
		scrollView.width = root.width - 20;
		scrollView.height = root.height - 70;
		scrollView.x = 10;
		scrollView.y = 60;
			
		var vertical = new Container();
		vertical.layout = new AbsoluteLayout();
			
		var incy = 0;
		for (i in 0...50) {
			var c = new Button();
			c.style.backgroundColor = 0xFFCC00;
			c.width = 150;
			c.height = 150;
			
			c.x = 10;
			c.y = incy;
			
			incy += 200;
			
			vertical.addChild(c);
		}
		
		vertical.height = incy;
		vertical.autoSize = true;
		
		scrollView.addChild(vertical);
		
		scrollView.visible = true;
		list.visible = !scrollView.visible;
		b.onClick = function(event) {
			b.text = 'Clicked ${Lib.getTimer()}';
			
			list.visible = !list.visible;
			scrollView.visible = !scrollView.visible;
		};
			
			
		root.addChild(list);
		root.addChild(scrollView);
	});
}
´´´

This code runs fast in scrollview:
´´´
public static function main():Void {	
		
	Toolkit.theme = new GradientMobileTheme();
	Toolkit.init();
	Toolkit.openFullscreen(function(root:Root) {
		var b:Button = new Button();
		b.text = "Test button";
		b.x = 10;
		b.y = 10;
		root.addChild(b);
		
		var quit:Button = new Button();
		quit.text = 'Quit';
		quit.x = root.width - 90;
		quit.y = 10;
		quit.onClick = function(e) {
			System.exit(0);
		}
		
		root.addChild(quit);
		
		var list = new ListView();
		list.x = 10;
		list.y = 60;
		
		list.inertialScrolling = true;
		list.width = root.width - 20;
		list.height = root.height - 70;
		
		for (i in 0...100) {
			list.dataSource.add( { text: 'Foo bar with a really really really \n long text to provoke a wrap line to check if it will perform slow on android \n wrap lines is not automatically in this one, so I\'m forcring a break \n and seeing if the performance is slower even with this long text that doesnt describe anything.. this is just to test the performance $i' } );
		}
			
		var scrollView = new ScrollView();
		scrollView.width = root.width - 20;
		scrollView.height = root.height - 70;
		scrollView.x = 10;
		scrollView.y = 60;
			
		var vertical = new Container();
		vertical.layout = new AbsoluteLayout();
			
		var incy = 0;
		for (i in 0...50) {
			var c = new Button();
			c.style.backgroundColor = 0xFFCC00;
			c.width = 150;
			c.height = 150;
			
			c.x = 10;
			c.y = incy;
			
			incy += 200;
			
			vertical.addChild(c);
		}
		
		vertical.height = incy;
		vertical.autoSize = true;
		
		scrollView.addChild(vertical);
		
		scrollView.visible = true;
		list.visible = !scrollView.visible;
		b.onClick = function(event) {
			b.text = 'Clicked ${Lib.getTimer()}';
			
			list.visible = !list.visible;
			scrollView.visible = !scrollView.visible;
		};
			
			
		root.addChild(list);
		root.addChild(scrollView);
	});
}
´´´

**Comment by ianharrigan** [comment]
Hmmm, all very strange... Leave it with me... You've given me more than enough use cases to test... And the fact it doesnt happen in ListView is verrrrry strange (as it uses scrollview). 

Ive been really caught up with work today, but ill hopefully get around to it sometime tomorrow / later tonight.

Thanks for the help (and the code!)

Cheers,
Ian

**Comment by marcelofrau** [comment]
Yes it is very strange. When I was making some tests with ListView I was expecting the same result, but the strange is that it runs much more smooth than the ScrollView itself.

Thanks, and if you need more help, code, or even if you are without time and indicate where the problem can possible be, I can take a look on the source also.

Best regards,

**Comment by ianharrigan** [comment]
... So i think i know what it is: I think its the filter performance... To prove thats the case, put this in your `application.xml`:

```xml
<set name="haxeui-filters-off" if="mobile" />
```
If that works, try a different override, eg:

```xml
<set name="haxeui-filters-low" if="mobile" />
```

From the `application.xml` from the template project:

```
set the filter quality to low for mobiles for better performance, values are:
		
		* haxeui-filters-off
		* haxeui-filters-low
		* haxeui-filters-medium
		* haxeui-filters-high
		
Remove flag to use whatever values are specified in the styles. 
```
Let me know if that helps/fixes it... 

Cheers,
Ian

**Comment by marcelofrau** [comment]
Hello..

Just tested and it worked! I'll use the filters-low and everything is working fine now.

Do you think this has any impact? Visually I didn't noticed anything compromised, do you think I can use the filters-low on a production software?

Haxe UI is great! :smile: 
Thank you very much for your help and support.

**Comment by ianharrigan** [comment]
It should be fine... Its just how many passes it uses for the filters... ie, the quality. Even on the desktop there is little visible difference since the shadows on the buttons are quite small... 

Glad it worked!

I remember i had a similar problem ages and ages ago and realised it was filter quality... Woke up this morning and remembed that

Cheers,
Ian
