### ISSUE TITLE
UIEvent.CHANGE not dispatched on ListSelector (only on default method)

### ISSUE THREAD

**Issue by loudoweb** [ianharrigan/haxeui#221]
I have a ListSelector working properly when I set the ListSelector.method = "popup".
But as soon I change the method to the "default", sometimes the UIEvent.CHANGE event is not dispatched when I click on an item.

EDIT : 
It's a really strange behavior because the MOUSE_OVER and MOUSE_OUT events from the ListView created by the ListSelector are always dispatched but the CLICK events works only sometimes.

EDIT 2 : 
It seems that the _onRootMouseDown from the ListSelector is dispatched and call hideList() event if we click on the list.

**Comment by ianharrigan** [comment]
hmmm, yeah, that does seems strange... Have you got a minimal example?

Cheers,
Ian

**Comment by loudoweb** [comment]
Thanks for your reply.

This is a minimal example (target flash) : 
```haxe
class Main extends Sprite 
{

	var _selectBox:ListSelector;
	
	public function new() 
	{
		super();
		
		// Assets:
		// openfl.Assets.getBitmapData("img/assetname.jpg");
		
		Toolkit.theme = new GradientTheme();
		Toolkit.init();
		
		var ui:Sprite = new Sprite();
		addChild(ui);
		ui.x = 25;
		ui.y = 130;
		
		
		var select:ListSelector = new ListSelector();
		select.method = "default";
		select.text = "Answer";
		select.width = 100;
		select.height = 25;
		for (i in 0...3)
		{
			select.dataSource.add( { text:"test" + i } );
			
		}
		_selectBox = select;
		
		
		Toolkit.openPopup( {parent:ui , width: 750, height: 435 }, function(root:Root) {
			//haxeui

			root.addChild(_selectBox);
			
        });
	}
}
```

**Comment by loudoweb** [comment]
I just tried further and it seems that using a parent Sprite for haxeui and changing its positions is not correct.

So I changed the previous code a little and this is working : 

'''haxe
class Main extends Sprite 
{

	var _selectBox:ListSelector;
	
	public function new() 
	{
		super();
		
		// Assets:
		// openfl.Assets.getBitmapData("img/assetname.jpg");
		
		Toolkit.theme = new GradientTheme();
		Toolkit.init();
		
		var ui:Sprite = new Sprite();
		addChild(ui);
		ui.x = 0;
		ui.y = 0;
		
		
		var select:ListSelector = new ListSelector();
		select.method = "default";
		select.text = "Answer";
		select.width = 100;
		select.height = 25;
		for (i in 0...3)
		{
			select.dataSource.add( { text:"test" + i } );
			
		}
		_selectBox = select;
		
		
		Toolkit.openPopup( {parent:ui , width: 700, height: 435 }, function(root:Root) {
			//haxeui
			root.x = 25;
			root.y = 130;
			root.addChild(_selectBox);
			
        });
	}
}
'''

I don't why.

**Comment by ianharrigan** [comment]
Hmm. Yes very strange indeed. Still you've managed to work out what the problem is so it should be easy now for me to see what the issue is. Nice one!

I'll check it out later this evening. 

Cheers,
Ian

**Comment by loudoweb** [comment]
Additional information: 

The last code doesn't work anymore if I change the scale of the parent.

ui.scaleX = ui.scaleY = 1.5;

**Comment by ianharrigan** [comment]
Sorry. In London atm... Will look into this (properly)  when I get back (2 days)

**Comment by loudoweb** [comment]
I looked closer to the code.

Hittest function use a custom stageX computation...
https://github.com/ianharrigan/haxeui/blob/master/haxe/ui/toolkit/core/DisplayObject.hx#L478

...which is wrong because it's missing root parent!
https://github.com/ianharrigan/haxeui/blob/master/haxe/ui/toolkit/core/DisplayObject.hx#L388

The root parent is located here : https://github.com/ianharrigan/haxeui/blob/master/haxe/ui/toolkit/core/RootManager.hx#L58
