### ISSUE TITLE
HTML5 build error (has no field loadFromHaxeBytes)

### ISSUE THREAD

**Issue by trsh** [ianharrigan/haxeui#229]
Tried to build Hellow word sample from haxeui git. Got error:

Error:(221, 14) Class<openfl.display.BitmapData> has no field loadFromHaxeBytes

Specs:

Compiled on Ubuntu 14.04 32bit

haxe: 3.1.3

Libs:
actuate: [1.8.3]
box2d: [1.2.3]
haxelib_client: [3.2.0-rc.3]
haxeui: [1.7.6]
hscript: [2.0.4]
hxcpp: [3.2.37]
layout: [1.2.0]
lime-samples: [2.2.0]
lime: [2.3.0]
openfl-samples: [2.2.2]
openfl: 3.0.0-beta [3.0.0-beta.3]
svg: [1.0.8]
swf: [1.8.2]
yagp: [1.1.4]

**Comment by ianharrigan** [comment]
Whoops, must have missed that... Ill fix that shortly.

Cheers!
Ian

**Comment by ianharrigan** [comment]
Do you mean hello-world in the samples folder? I cant seem to be able to reproduce this, i get the following:

![output](https://cloud.githubusercontent.com/assets/3024242/7002257/474497b8-dc48-11e4-9c7b-16f83f2bc27e.png)

Do you have a full stack trace?

Cheers,
Ian

**Comment by trsh** [comment]
Can't get the full stack :/

trsh@trsh-laptop:~/IdeaProjects/qe$ haxelib run openfl build application.xml html5 -debug
/usr/lib/haxe/lib/haxeui/1,7,6/haxe/ui/toolkit/controls/Image.hx:221: characters 14-42 : Class<openfl.display.BitmapData> has no field loadFromHaxeBytes

<haxedef name="HXCPP_STACK_TRACE" />
	<haxedef name="HXCPP_STACK_LINE" />
	<haxedef name="HXCPP_DEBUG_LINK" />

are added

**Comment by trsh** [comment]
Sample from https://github.com/ianharrigan/haxeui/tree/master/samples/hello-world

**Comment by trsh** [comment]
I just did a haxelib upgrade (again) and the Build run clean :) .. something somewhere somehow got fixed

**Comment by ianharrigan** [comment]
Ok, fair enough, i do remember fixing an issue with loading remote images on html (http://*) so its possible i fixed that then. Think this is closable?

**Comment by trsh** [comment]
Yes. Good job! One question. The exported example to html5 seem to have no style for the button (no shadows, nice font, etc). Why is that?

**Comment by ianharrigan** [comment]
Cool. Ill close it then,

Re the question, html5 isnt really supported at the moment, there are quite a few problems to be fair (scrollview and listview come straight to mind)... hopefully that doesnt break your use case, but as it stands, html5 isnt really up to the job.

Openfl next will hopefully remedy something of this/that with webgl though. 

Cheers,
Ian

Ps: A screen shot would be great btw if you have one! :)

**Comment by trsh** [comment]
Mhm.. In http://haxeui.org/examples/html/showcase/index.html buttons look OK. Mine
![screenshot from 2015-04-06 19 57 07](https://cloud.githubusercontent.com/assets/3727523/7007965/34d3eb7a-dc97-11e4-9dd1-1dad27cfc2a0.png)

**Comment by trsh** [comment]
It's bad news for me for the HTML5 not being really supported :( ..  I hope it changes soon.

**Comment by ianharrigan** [comment]
Yeah, seems about right. No shadows (filters) and no gradient fills... :(

**Comment by ianharrigan** [comment]
Sorry about that @trsh but html5 really isnt something that im willing to put serious effort into until the various backends stabalise a little (pixi, webgl, dom, etc). At present haxeui works badly with all of them. Not sure what to advise, but html is a real (and increasing) problem at the moment.

**Comment by trsh** [comment]
Your saying, right now, the ball is on OpenFL side?
