### ISSUE TITLE
TextFields not worked in popups, cpp\neko

### ISSUE THREAD

**Issue by dmitryhryppa** [ianharrigan/haxeui#230]
Hi there!
TextFields not worked inside PopUps, I can set the cursor inside, but can not type any text. 
With flash terget all is fine. 

Openfl 3.0, with -Dv2 flag

**Comment by ianharrigan** [comment]
Hi, sorry for the late reply!

I dont suppose you have a quick and easy code snippet that shows this do you? Certainly seems strange.

Cheers,
Ian

**Comment by dmitryhryppa** [comment]
Yep, here is a simple code. Compiled with **lime test neko -Dv2** and last openfl

		Toolkit.theme = new GradientTheme();
		Toolkit.init();		
		Toolkit.openFullscreen(function(root:Root) {	
			var textInput:TextInput = new TextInput();			
			//root.addChild(textInput); //<< worked
			
			var controller:CustomPopupContent = new CustomPopupContent(textInput);			
			PopupManager.instance.showCustom(controller, "Title");			
		});

When I try to input text in the textfield got: 

Invalid operation (&)
Called from haxe/ui/toolkit/core/PopupManager.hx line 184
Called from haxe/ui/toolkit/core/PopupManager.hx line 47
Called from openfl/_legacy/events/EventDispatcher.hx line 98
Called from openfl/_legacy/display/DisplayObject.hx line 182
Called from openfl/_legacy/display/DisplayObject.hx line 258
Called from openfl/_legacy/display/Stage.hx line 824
Called from openfl/_legacy/display/Stage.hx line 381

Then I change 184 line of PopupManager from
if (p.config.dismiss **&** action > 0) {
to 
if (p.config.dismiss **&&** action > 0) {
and error was gone. 

But, do the compile again with **lime test neko -Dv2** and you will can not put any text to the text field. 
On flash target it works fine.

Thanks for help :+1:

**Comment by hazagames** [comment]
This problem appears after version 1.7.1. Maybe we can compare the related source code of this version to the later versions to spot and fix the problem. I tried but not familiar enough with the inner structure of HaxeUI so I didn't have any success yet.

**Comment by ianharrigan** [comment]
Ok, ill check it out shortly. Are you using openfl next?

**Comment by dmitryhryppa** [comment]
I'm using latest openfl with legacy mode (-Dv2).

**Comment by ianharrigan** [comment]
OK, fair enough, ill check it out in a moment.

Cheers,
Ian

**Comment by ianharrigan** [comment]
Can you try that with the latest version (1.7.12), it seemed a PR wasnt properly thought out and was intercepting keypresses and doing incorrect aritmetic on nulls.

Should work fine now.

(this is also related to #239)

**Comment by ianharrigan** [comment]
If that fixes it can you either close it or let me know so i can close it?

Cheers,
Ian

**Comment by dmitryhryppa** [comment]
Thank you, Ian!
Now issue is gone, popups works perfect. 
:+1:

**Comment by ianharrigan** [comment]
Great! Good news. Glad its working!

Cheers,
Ian
