### ISSUE TITLE
Error: No completion point was found when used buildController Macro

### ISSUE THREAD

**Issue by kevinresol** [ianharrigan/haxeui#234]
If a class uses the build macro `buildController` the code completion does not work on FlashDevelop

```
Error: No completion point was found
```

However it compiles well.

Edit: strange enough, the completion only fails within the contructor. It completes well in other functions and outside the class.

**Comment by ianharrigan** [comment]
Ive noticed this also, i havent really investigated to be honest. I wonder if it has something to do with use haxes completion server? Not really sure... Any thoughts?

Cheers,
Ian

**Comment by kevinresol** [comment]
Just a guess, it is due to the manipulation of the constructor inside the
build macro?

**Comment by kevinresol** [comment]
Let's focus the efforts on v2
