### ISSUE TITLE
Update to OpenFL 3.0.1

### ISSUE THREAD

**Issue by icek** [ianharrigan/haxeui#237]
haxeui requires dependency of openfl-3.0.0-beta while official haxelib release is now 3.0.1

**Comment by ianharrigan** [comment]
Cool... ill update now.

Cheers,
Ian

**Comment by ianharrigan** [comment]
Ok, that should be sorted now in the latest version (1.7.10)... Let me know if you have any issues?

Shall i close this? Or do you want to?

Cheers,
Ian

**Comment by icek** [comment]
Thank you!

**Comment by ianharrigan** [comment]
No probs! Thanks for reminding me! :)
