### ISSUE TITLE
Cannot input text in popup

### ISSUE THREAD

**Issue by kevinresol** [ianharrigan/haxeui#239]
Following the instruction for "Custom Contents" popup [here](http://haxeui.org/wiki/en/Using_Popups). The popup with textinput shows properly but I cannot input/alter any text in the textinput

**Comment by ianharrigan** [comment]
possibly related to #230

**Comment by ianharrigan** [comment]
Can you try that with the latest version (1.7.12), it seemed a PR wasnt properly thought out and was intercepting keypresses and stopping propogation of events.

**Comment by ianharrigan** [comment]
If that fixes it can you either close it or let me know so i can close it?

Cheers,
Ian

**Comment by kevinresol** [comment]
It is working now

**Comment by ianharrigan** [comment]
Cool... Good stuff!

Cheers,
Ian
