### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by StephenKDS** [ianharrigan/haxeui#266]
For some reason using HaxeUI - it appears to ignore any attempt to make my application (Android build testing), in portrait. its forcing it to be landscape.

Is there something I'm missing?

**Comment by ianharrigan** [comment]
Hi sorry for the late reply, been busy and away for the weekend. It should work fine, it works for me at least. I do remember there was something that needed to be added in openfl to make it work, i think it might be something like this:

```xml
<window background="#FFFFFF" fps="60" hardware="true" />
<window width="800" height="600" unless="mobile" />
<window orientation="landscape" vsync="false" antialiasing="0" if="cpp" />
```

Let me know of that helps

**Comment by StephenKDS** [comment]
I've done that - it is included in the OpenFL template project XML file.

Still couldn't get it using portrait orientation. :-/ This is difficult. do you have a sample/example app that works in portrait that you could share with me?

**Comment by ianharrigan** [comment]
are you using flash develop? The template for that should handle orientation changes.

**Comment by StephenKDS** [comment]
Yes, and it's not affecting it. Just seems to be forcing landscape.

**Comment by ianharrigan** [comment]
hmmmm... very strange. Do other (non-openfl / non-haxeui) work? What about normal openfl (ie, no haxeui)

**Comment by ianharrigan** [comment]
what about removing this line: 

```xml
<window orientation="landscape" vsync="false" antialiasing="0" if="cpp" />
```

**Comment by StephenKDS** [comment]
I have mine set to portrait. I have it working fine in other openfl projects. Just this one using HaxeUI seems to be having issues.

**Comment by ianharrigan** [comment]
what if you remove the line altogether?

**Comment by StephenKDS** [comment]
I'll give it a try tonight.

**Comment by StephenKDS** [comment]
sorry for the delay - tried removing. no difference. still forcing landscape orientation. :-/

**Comment by ShaheedLegion** [comment]
That's very interesting, I have an app which uses a very similar setup, and it's working fine - obviously I have my device set to allow for orientation changes
Notice that I've not included the orientation keyword - this allows the app to use the device orientation.

        <window background="#000000" fps="60" />
	<window width="600" height="800" unless="mobile" />
	<window vsync="false" antialiasing="0" if="cpp" />

**Comment by ShaheedLegion** [comment]
So, I looked at your project - your android manifest file contains this line: android:screenOrientation="sensorLandscape"

This tells the activity to remain in landscape or "reverse landscape" no matter what.
Try removing that line to fix your problem.

I don't have haxe-webui installed, but I'll take a pretty big bet that's the cause of your troubles.

**Comment by StephenKDS** [comment]
Ah crap. Okay something I've overlooked. I'll try it and see if it resolves
my issue.

Much appreciated :)

**Comment by ShaheedLegion** [comment]
No problem, I've looked through all your code, and I can't see anything else in there that would force your orientation, so I hope you win.

**Comment by StephenKDS** [comment]
Am trying it right now, so will let you know if its all good :)

**Comment by StephenKDS** [comment]
Bingo, bango.. you got it. Fixed the orientation issue. Thanks for your
help!

**Comment by ShaheedLegion** [comment]
No problem, have fun with your great project, can't wait to see it when it's done.

**Comment by StephenKDS** [comment]
Thanks! :) I've been waiting for this to resolve, so I could move forward
building apps cross-platform instead of games.

Regards,
Stephen

**Comment by ianharrigan** [comment]
Thanks @ShaheedLegion! :)
