### ISSUE TITLE
Dynamic font-size in CSS doesn't work

### ISSUE THREAD

**Issue by roughee** [ianharrigan/haxeui#269]
I found an example how to get font-size to scale with client dpi:
https://groups.google.com/d/msg/haxelang/6yF8usGwC1Y/5Ng_Q-rfK_0J
```
<vbox>
    <style>
        #theButton {
            fontSize: (Client.dpi / 4) + 10;
        }
    </style>
    <button text="Button" id="theButton" />
</vbox>
```

But it doesn't seem to work properly. In flash the text ends up being very small, in html5 it is a little bigger, but it fails to respond to screen changes. Same behavior in the Builder.

I also tried Client.instance.dpi and Client.get_instance().get_dpi()

If I call it from the code `var dpi = Client.instance.dpi;` it will return the dpi properly.

Any work-around to get this working?

**Comment by ianharrigan** [comment]
What does the Client.dpi return? Ie, what is the dpi you are working with?

**Comment by roughee** [comment]
Client.dpi returns 96 from code.

I also tried (Client.screenHeight / 4) + 10 and even if I refresh the browser page at different sizes, doesn't seem to change the fontSize.

http://haxeui.org/try.jsp?layoutId=nMrjG44

Could I get a working example?

**Comment by ianharrigan** [comment]
Yeah, that doesnt seem right. My gut says that Client.X is failing and returning something strange. Checking now locally. Ill let you know.

**Comment by ianharrigan** [comment]
Ok, got it. The issue is im adding the ClientWrapper as a static object, and its not, it should be an instance. Im going to push a fix now, do you use haxelib?

**Comment by ianharrigan** [comment]
Ok, try that now, you'll need latest haxelib version.

**Comment by roughee** [comment]
Ok, looks like it works properly. 

How would you make text resize when window resizes?
Make a window height listener and then merge styles with new font size?

Also a notice new openfl 3.1.1 changed fontSize from float to Int. (https://github.com/openfl/openfl/blob/master/CHANGELOG.md)
```C:/HaxeToolkit/haxe/lib/haxeui/1,7,14/haxe/ui/toolkit/text/TextDisplay.hx:105: characters 3-32 : Float should be Null<Int>
C:/HaxeToolkit/haxe/lib/haxeui/1,7,14/haxe/ui/toolkit/text/TextDisplay.hx:105: characters 3-32 : Float should be Int```
a temp fix I wrapped around in Std.int
```format.size = Std.int(_style.fontSize);```

**Comment by ianharrigan** [comment]
Ok, there was another bug, it was that the client gets instanciated, copies over properties, like screenHeight, and never updates them, ive updated to stop using the wrapper now, which was is essentially usless, and just talk to the raw Client object. As for updating as values change, there are two options, none of which im particularly happy with.

* From code:
```haxe
var box:Component = Toolkit.processXmlResource("ui/main.xml");
root.addChild(box);
root.addEventListener(UIEvent.RESIZE, function(e:UIEvent) {
	box.invalidate(InvalidationFlag.ALL, true);
});
```

where `ui/main.xml` is:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<vbox id="main">
	<style>
	        #test1 {
	            fontSize: (Client.windowHeight / 8);
	        }
	        #test2 {
	            fontSize: (Client.windowHeight / 10);
	        }
	        #test3 {
	            fontSize: (Client.windowHeight / 12);
		}
	</style>
	<button text="Button" id="test1" />
	<button text="Button" id="test2" />
	<button text="Button" id="test3" />
</vbox>
```

* From script (does the same thing really, but from script):
```xml
<?xml version="1.0" encoding="utf-8" ?>
<vbox id="main">
	<style>
		#test1 {
			fontSize: (Client.windowHeight / 8);
		}
		#test2 {
			fontSize: (Client.windowHeight / 10);
		}
		#test3 {
			fontSize: (Client.windowHeight / 12);
		}
    	</style>
	<script>
		main.root.onResize = function(e) {
			main.invalidate(0x0100000, true);
		}
	</script>
	<button text="Button" id="test1" />
	<button text="Button" id="test2" />
	<button text="Button" id="test3" />
</vbox>
```

I dont like either approach if im honest as they both require manually invalidating the control, which i would prefer to automatically happen, still, they work. Im currently working on version 2, which is vastly different, so i will keep in mind use cases like this (although at the moment, css in v2 cant be dynamic values anyway)

**Comment by ianharrigan** [comment]
Sorry, forgot to mention, none of that will work without another `haxelib update haxeui`

**Comment by roughee** [comment]
ok thank you, I'm closing this :+1: for quick fixes
