### ISSUE TITLE
Using checkboxes in itemrenderers

### ISSUE THREAD

**Issue by Mechameesh** [ianharrigan/haxeui#275]
I've got a few listviews with custom itemrenderers containing checkboxes (amongst other controls). I find that extracting information about value changes in these checkboxes to be a bit cumbersome. 

Listening for a UIEvent.COMPONENT_EVENT on a listview gives the following event data:

e.data has not been updated yet with the proper values as the dispatchProxyEvent in the itemrenderer fires before the UI sync, and the UIEvent.CHANGE event for listviews is dedicated to selection changes rather than itemrenderer changes.

e.component is the corresponding Button component in the following chain (inheritance and children):
itemrenderer->checkbox->checkboxvalue->Value->values->Button, and has not yet updated the parent container (i.e. checkboxvalue)

Is there a better way of extracting the updated value of the checkboxes in the itemrenderer, or am I going about this all wrong?

**Comment by ianharrigan** [comment]
Leave it with me and ill get back to you later tonight, im pretty sure i did the same thing, im just not 100% sure off the top of my head how i did it.

**Comment by ianharrigan** [comment]
Actually, i dont have an example, i only have read only check boxes from an external data source. Ill have another play tomorrow / later tonight. Do you have a minimal example of what you are using? (Might save me sometime). I have a feeling here is something to do with it: https://github.com/ianharrigan/haxeui/blob/master/haxe/ui/toolkit/core/renderers/ItemRenderer.hx#L97-L116,

But ill need to create a test project to confirm that. Bear with me, checkboxes in lists its pretty important! ;)

**Comment by Mechameesh** [comment]
I whipped up a quick example which now works here:
https://github.com/Mechameesh/HaxeUICheckBoxTest

some issues which might be worth looking at are commented in this class:
https://github.com/Mechameesh/HaxeUICheckBoxTest/blob/master/src/TestItemRenderer.hx

**Comment by ianharrigan** [comment]
Superb, thanks! Leave it with me! +1

**Comment by ianharrigan** [comment]
Really sorry for the delay, i will get back to you asap! ;)

**Comment by Mechameesh** [comment]
Hey, no worries =)

**Comment by ianharrigan** [comment]
Just to let you know, im looking at this now... Great demo btw, make it so much easier to sort things out when i dont have to recreate the issue. I notice there is a problem with disabled checkboxes also

**Comment by Mechameesh** [comment]
Thanks. Yeah, there seems to be problem with itemrenderer styles being overwritten by the mouseover events from the listview. I'm assuming this will be the case for all children you put in an itemrenderer

**Comment by ianharrigan** [comment]
That should be working correctly now, you now no longer actually need your item renderer class with the overrides, you can still use it of course, but it should now be much simpler. And example can be found here: http://haxeui.org/try.jsp?layoutId=akaG8Lz

This does exactly the same (i think / hope) as what you are doing, but with no custom classes, just a single xml file. 

Let me know if that helps!

Cheers,
Ian

**Comment by ianharrigan** [comment]
Meant to add, thats haxelib version 1.7.16

**Comment by Mechameesh** [comment]
Great! Thanks =)
