### ISSUE TITLE
fresh install of haxeui not working

### ISSUE THREAD

**Issue by martindemello** [ianharrigan/haxeui#279]
I installed lime, openfl and haxeui according to the instructions in http://haxeui.org/install_openfl.jsp. Trying out the hello world example fails with:

````
$ openfl test neko

/home/mdemello/opt/share/haxe/lib/haxeui/1,7,16/haxe/ui/toolkit/core/Root.hx:90: characters 3-24 : haxe.ui.toolkit.core.Component has no field onClick
/usr/lib/haxe/std/neko/_std/sys/io/File.hx:30: characters 20-51 : styles/gradient/gradient.css: No such file or directory
/home/mdemello/opt/share/haxe/lib/haxeui/1,7,16/haxe/ui/toolkit/core/Macros.hx:572: characters 24-60 : Called from
./Main.hx:11: characters 8-60 : Called from
Aborted
````

installed libs:

````
$ haxelib list
actuate: [1.8.6]
box2d: [1.2.3]
csv: [0.4.0]
format: [3.1.2]
haxelib_client: [3.2.0-rc.3]
haxeui: [1.7.16]
hscript: [2.0.4]
hxargs: [3.0.0]
hxcpp: [3.2.102]
layout: [1.2.1]
lime-samples: [2.6.0]
lime: [2.6.1]
openfl-samples: [3.3.0]
openfl: [3.3.2] 3.3.1
svg: [1.0.8]
swf: [2.0.1]
yagp: [1.1.4]
````

(the openfl version 3.3.2 was installed by lime and 3.3.1 as a dependency of haxeui; i tried setting `	<haxelib name="openfl" version="3.3.1"/>` in application.xml but that still didn't work)

````
haxe -version #=> 3.3.0
OpenFL Command-Line Tools (3.3.2-LPR0DW)

**Comment by ianharrigan** [comment]
What happens if instead of:

```haxe
Macros.addStyleSheet("styles/gradient/gradient.css");
```

You use:

```haxe
Toolkit.theme = new GradientTheme();
```

Also, can you paste in your entire test app? 

Cheers,
Ian

**Comment by martindemello** [comment]
still doesn't work. here's my test app, directly from the hello world example:

````
$ cat Main.hx 
package;

import haxe.ui.toolkit.core.Macros;
import haxe.ui.toolkit.core.Toolkit;
import haxe.ui.toolkit.core.Root;
import haxe.ui.toolkit.controls.Button;
import haxe.ui.toolkit.events.UIEvent;
 
class Main {
    public static function main() {
        Toolkit.theme = new GradientTheme();
        Toolkit.init();
        Toolkit.openFullscreen(function(root:Root) {
            var button:Button = new Button();
            button.text = "Click Me!";
            button.x = 100;
            button.y = 100;
            button.onClick = function(e:UIEvent) {
                e.component.text = "You clicked me!";
            };
            root.addChild(button);
       });
    }
}
````
````
$ cat application.xml 
<?xml version="1.0" encoding="utf-8"?>
<project>
	<meta title="Hello World" package="" version="1.0.0" company="" />

	<app main="Main" file="hello_world" path="bin" />
	
	<window background="#FFFFFF" fps="60" />
	<window width="800" height="600" unless="mobile" />
	<window orientation="landscape" vsync="false" antialiasing="0" if="cpp" />
	
	<!-- classpath, haxe libs -->
	<source path="." />
	<haxelib name="openfl" version="3.3.1"/>
	<haxelib name="actuate" />
	<haxelib name="hscript" />
	<haxelib name="haxeui" />
</project>
````

and compiling:

```` openfl build neko

/home/mdemello/opt/share/haxe/lib/haxeui/1,7,16/haxe/ui/toolkit/core/Root.hx:90: characters 3-24 : haxe.ui.toolkit.core.Component has no field onClick
./Main.hx:11: characters 24-43 : Type not found : GradientTheme
./Main.hx:18: characters 12-26 : haxe.ui.toolkit.controls.Button has no field onClick
````

**Comment by ianharrigan** [comment]
Hmmm, very strange. You are missing an import:

```haxe
import haxe.ui.toolkit.themes.GradientTheme;
```

After i add that, it works fine. I dont quite understand the onClick issue. It almost seems like Macros arent working (as that onClick is added via macros)

**Comment by ianharrigan** [comment]
What happens if you replace the "onClick" with:

```haxe
            button.addEventListener(UIEvent.CLICK, function(e:UIEvent) {
                e.component.text = "You clicked me!";
            });
```

?

**Comment by martindemello** [comment]
thanks, fixed the import issue and updated comment. the onClick still isn't working for me. i tried replacing it with addEventListener in my code, which works for that error, but it still breaks when Root.hx calls _modalOverlay.onClick = ...

**Comment by ianharrigan** [comment]
Hmmm, very strange. I wonder if you dont mind debugging it a little? As i said, it seems like macros arent running on your install, which is very strange. If you open the class:

```
haxe.ui.toolkit.core.Macros
```

and on line 174 there is a function "addEvents", if you add a trace there, something like:

```haxe
trace(">>>>>>>>>>>>>>>>>>>>>> ADDING EVENTS");
```

Do you ever see that trace output?

**Comment by martindemello** [comment]
I was just adding traces to that. It looks like events only has one entry:

````
    trace(types);
    for (type in types) {
      //addEvent(type, fields);
      var name = "on" + StringUtil.capitalizeFirstLetter(type);
      trace('adding event $name');
````

prints

````
/home/mdemello/opt/share/haxe/lib/haxeui/1,7,16/haxe/ui/toolkit/core/Macros.hx:178: [componentEvent]
/home/mdemello/opt/share/haxe/lib/haxeui/1,7,16/haxe/ui/toolkit/core/Macros.hx:182: adding event onComponentEvent
````

**Comment by martindemello** [comment]
looks like it's being invoked from ListView but not from DisplayObject

**Comment by ianharrigan** [comment]
Yeah, very strange, what version of haxe are you using?

**Comment by martindemello** [comment]
3.3.0 installed from git head

**Comment by ianharrigan** [comment]
I wonder if that is something to do with it? Im on 3.2.0... Could it be a regression?

**Comment by martindemello** [comment]
let me try checking out 3.2 and retrying

**Comment by ianharrigan** [comment]
Nice one, thanks... certainly bizarre behaviour.

**Comment by martindemello** [comment]
yep, works perfectly with 3.2.1. weird sort of regression; i'll file a bug with haxe if i can figure out what's going on.

**Comment by ianharrigan** [comment]
Superb... Well, not superb... :)

Thanks for investigating.

Cheers,
Ian

**Comment by dhemitus** [comment]
so, the bugs in haxe 3.3.0? because i had same problem. and in very new in haxeui

**Comment by dhemitus** [comment]
you should replace this in Root class
_modalOverlay.onClick = function(e) {
with this to
_modalOverlay.addEventListener(UIEvent.CLICK, function(e:UIEvent) {

**Comment by ianharrigan** [comment]
Yeah, but that isnt the full problem i dont think, thats a patch / workaround - the problem is in haxe 3.2.1, if you downgrade to 3.2.0 everything should work.

**Comment by colbyrussell** [comment]
Why is this issue marked closed if the example on haxeui.org is still broken?

I also emailed @ianharrigan about broken links in the "Getting Started" pages.
