### ISSUE TITLE
Support touch based scrolling in listviews and scrollviews on mobile devices.

### ISSUE THREAD

**Issue by sebthom** [ianharrigan/haxeui#285]
Currently scrolling only seems to be possible by using the scroll bars which is counter intuitive on mobile.

**Comment by ianharrigan** [comment]
They should work fine with touch also... Al scrollviews on v1 respond to "drag scrolling" also

**Comment by ianharrigan** [comment]
for example: http://haxeui.org/try.jsp?layoutId=aK9eAzB

You can use the scrollbar or you can drag the list up and down... All lists a scrollviews behave like this

**Comment by sebthom** [comment]
Ok I have an app on Android 5.0.1 with a scrollview containing a single text component. when the text component has more lines than the scrollview can hold the scrollbar is displayed and scrolling only works when tapping on the scrollbar.

The xml looks like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <vbox id="system" height="800" width="450">
    	<scrollview width="100%" height="100%" showVScroll="true" showHScroll="false" style="borderSize:0" inertialScrolling="true">
    		<vbox width="100%">
    			<text id="log" wrapLines="true" text="Initializing..." multiline="true" autoSize="true" width="100%" />
    		</vbox>
    	</scrollview>
    </vbox>

I am using haxeui 1.7.18 and the gradient theme.

**Comment by ianharrigan** [comment]
try and remove the "100%" from your vbox... as that is telling it to be 100% of the scrollview, but you want it to resize to be bigger than it

**Comment by ianharrigan** [comment]
Sorry, actually, thats not accurate... its the width that is set in the vbox...

**Comment by sebthom** [comment]
Can I enable some kine of debugging? Are there events I can listen to regarding the touch scrolling?

**Comment by ianharrigan** [comment]
`UIEvent.SCROLL` should be dispatched... this works in the builder: http://haxeui.org/try.jsp?layoutId=az8nnao

**Comment by ianharrigan** [comment]
Also, try something like this (where i have set the background color), it may be that its not getting events for some reason: http://haxeui.org/try.jsp?layoutId=nyxgB7R

**Comment by sebthom** [comment]
That did the trick! Setting the background color enables scrolling. Thanks!
Maybe this should be documented somewhere. :-)

**Comment by ianharrigan** [comment]
Yeah, i think this is a probem in flash in general... ive seen it before where you only get events for things that actually have graphics in them (even if alpha is 0)...

Should probably be document somewhere , you are right.

Glad it worked!

**Comment by sebthom** [comment]
I added a remark in the wiki http://haxeui.org/wiki/en/Scroll_Views

**Comment by ianharrigan** [comment]
Superb... thanks!
