### ISSUE TITLE
Fonts and styles are included twice on android builds

### ISSUE THREAD

**Issue by sebthom** [ianharrigan/haxeui#286]
When generating the apk file some of the Haxe UI resources (styles and fonts) are included twice in the apk.
Under  the bin/android/bin directory and inside the APK file it looks like this:

    assets
    ├───assets                                                   
    │   ├───fonts                                                
    │   │       Oxygen-Bold.eot                                  
    │   │       ...
    │   └───styles                                               
    │       ├───default                                          
    │       │       circle.png                                   
    │       │       ...                              
    │       ├───gradient                                         
    │       │       arrow_down.png                               
    │       │       ...
    │       └───windows                                          
    │           │   accordion.css                                
    │           │   ...
    │           └───glyphs                                       
    │                   down_arrow.png                           
    │                   ...
    ├───fonts                                                    
    │       Oxygen-Bold.eot                                      
    │       ...                                                 
    ├───styles                                                   
    │   ├───default                                              
    │   │       circle.png                                       
    │   │       ...
    │   ├───gradient                                             
    │   │       arrow_down.png                                   
    │   │       ...
    │   └───windows                                              
    │       │   accordion.css                                    
    │       │   ...
    │       └───glyphs                                           
    │               down_arrow.png                               
    │               ...

**Comment by ianharrigan** [comment]
Ill have to check this out... Not sure why its happening, but will check it out

**Comment by ianharrigan** [comment]
What does you application.xml look like?

**Comment by ianharrigan** [comment]
Can you try the latest haxelib version (v1.7.20)... also if you have any of these:

```xml
<assets path="assets" embed="true" rename="assets"/>
``` 

or

```xml
<assets path="assets" rename="assets"/>
``` 

in your `application.xml` then remove them. Ive updated the FD template also.

**Comment by sebthom** [comment]
Removing the assets path declaration did the trick. thanks!
