### ISSUE TITLE
Add option to disallow dragging of popups

### ISSUE THREAD

**Issue by sebthom** [ianharrigan/haxeui#288]
I'm displaying a popup on mobile using PopupManager.showSimple(). I don't want the user to be able to drag the popup around as this has no user benefit and is untypical on mobile devices. Please add an option to disable dragging around of popups. Thanks

**Comment by ianharrigan** [comment]
Yeah, good call, will get round to this today at some point... its an easy fix as there is already a system in place for this (Popup::allowDrag) but its just not used to stop drag, just allow it on the whole popup or just the title... will be trivial to disallow drag.

**Comment by sebthom** [comment]
If I am doing this now:

    PopupManager.instance.showSimple("text", "title", {disableDrag:true});

the simple popup is displayed without any buttons.
