### ISSUE TITLE
TextDisplay.set_text implementation looks buggy

### ISSUE THREAD

**Issue by sebthom** [ianharrigan/haxeui#289]
While trying to understand something else in haxeui I came across these lines in **haxe.ui.toolkit.text.TextDisplay**. 

    private function set_text(value:String):String {
    		if (value != null) {
    			if (_tf.multiline == false) {
    				_tf.text = StringTools.replace(value, "\\n", "\n");
    			} else {
    				_tf.text = StringTools.replace(value, "\\n", "\n");
    			}
    		}

-> StringTools.replace is invoked with exactly the same parameters in both cases if multiline is **true** or **false**. Is this by intention?

**Comment by ianharrigan** [comment]
Yeah, seems like old code... Will fix this later today
