### ISSUE TITLE
Option to not include any HaxeUI assets in build result

### ISSUE THREAD

**Issue by sebthom** [ianharrigan/haxeui#294]
For one app I created a custom theme and don't need any of the HaxeUI resource files.

It seems impossible by configuration to exclude all assets (ttf, png, css) from the final build (in my case an Android APK).

Currently I am manually commenting out all asset sections in haxeui's include.xml

This however has the side effect that now for all projects using haxeui the assets are excluded.

Can we have for example another flag similar to haxeui-embed-resources but that allows the forced exclusion of all haxeui assets?

**Comment by sebthom** [comment]
I am doing this for now in haxeui's include.xml:

	<section unless="haxeui-exclude-resources">
		
		<section if="haxeui-embed-resources">
			<assets path="assets/styles" embed="true" rename="styles"/>
			<assets path="assets/fonts" embed="true" rename="fonts"/>
			<haxedef name="haxeui-embed-resources"/>
		</section>

		
		<section unless="haxeui-embed-resources">
			<assets path="assets/styles" rename="styles"/>
			<assets path="assets/fonts" rename="fonts" />
		</section>
	</section>

**Comment by ianharrigan** [comment]
Does that mean you have a totally custom css?

**Comment by sebthom** [comment]
I created a custom theme (I basically just themed the few widgets I am using) and registered it by providing a custom module.xml file in the class path. I hope that is appropriate!

**Comment by ianharrigan** [comment]
Yeah, i cant see any harm in this... Fancy issuing a pull request?

Cheers,
Ian
