### ISSUE TITLE
Option/CheckBox :down style

### ISSUE THREAD

**Issue by sebthom** [ianharrigan/haxeui#295]
Is it possible to change the background color of an option/checkbox widget the moment a user clicks the option?

I hoped I could do something like this:

    OptionBox:down {
        backgroundColor:0xFF00FF;
    }

but it doesn't work. This would be esp. nice since now the option box label is clickable.

**Comment by ianharrigan** [comment]
I guess the best way to do this would be to apply different styles (using "styleName") based on what you want, no? Or do you mean something like when the user holds the mouse down, it changes color, and then when the mouse is up, it changes back to the original?

**Comment by sebthom** [comment]
It basically should work like for a button. When I click the button on the text or the image the whole rectangle surrounding the content is highlighted to give a visual feedback about the touched object.
So when I specify an "Option:down" style I'd like to see the option image (the bullet/circle) plus the text being highlighted.

**Comment by ianharrigan** [comment]
should be fixed, example here: http://haxeui.org/try.jsp?layoutId=jKqxLRa

**Comment by sebthom** [comment]
Nice! Thanks.
