### ISSUE TITLE
link is opened even if link is not visible

### ISSUE THREAD

**Issue by sebthom** [ianharrigan/haxeui#296]
When a link is for example hidden/overlayed by button (e.g. because of a stackview, scrollview) and one clicks the button the click event is also passed on to the hidden link and the browser is opened. Using event.stopPropagation or stopImmediatePropagation in the buttons event handler does not help.

**Comment by ianharrigan** [comment]
Im not quite sure i follow... Do you have some example code / xml of what you mean?

**Comment by ianharrigan** [comment]
Ah, although, looking at the impl for Link i can see what is happening

**Comment by sebthom** [comment]
try to click the link in this example:

    <?xml version="1.0" encoding="UTF-8"?>
    <stack width="100%" height="100%">
    	<vbox width="100%" height="100%">
		    <button text="hello" />
	    </vbox>
    	<vbox width="100%" height="100%">
	    	<link text="http://archive.org/" style="fontSize:30" />
    	</vbox>
    </stack>

**Comment by sebthom** [comment]
Is there any easy workaround for this?

**Comment by ianharrigan** [comment]
Ill take a look at this over the weekend.

**Comment by ianharrigan** [comment]
Should be fixed now

**Comment by sebthom** [comment]
Looks like there is another corner case: The link is in a scroll view and fully or partially outside the scroll area, directly below the scroll view is a button. When you click the button while the URL is located below it, the link will open.

Examples:

   http://haxeui.org/try.jsp?layoutId=ybanL4n

   http://haxeui.org/try.jsp?layoutId=85oRAo8

**Comment by ianharrigan** [comment]
Hmmm, yeah... good catch...

**Comment by ianharrigan** [comment]
Should be fixed now: http://haxeui.org/try.jsp?layoutId=np8pn7d

**Comment by sebthom** [comment]
Works. Thanks!
