### ISSUE TITLE
haxeui.org is down

### ISSUE THREAD

**Issue by jamiltron** [ianharrigan/haxeui#297]
Cannot access the wiki or api.

**Comment by ianharrigan** [comment]
Yeah, talking to the provider now

**Comment by mpoint4u** [comment]
Yeah, still down ...

**Comment by ianharrigan** [comment]
Yeah, its a big problem. The provider has now stopped answering calls... :/

**Comment by mpoint4u** [comment]
Of course that's your cup of coffee ... I would change the provider in this case ... ;-)

**Comment by ianharrigan** [comment]
yeah, changing provider now, just building the server OS... should be up some time later today...

**Comment by jamiltron** [comment]
It's looking good to me!

**Comment by mpoint4u** [comment]
It's loading faster then before now ...))

**Comment by ianharrigan** [comment]
Yeah, seems like a better company for sure, and its still the lowest spec machine they have, so certainly room for growth.

**Comment by geekbozu** [comment]
It seems like the wiki is still down. It directs to an Apache tomcat 404 page. The API pages are up, as well as seemingly everything else.
