### ISSUE TITLE
haxe 3.2.1/hxcpp compilation error

### ISSUE THREAD

**Issue by r3d9u11** [ianharrigan/haxeui#326]
Hi, I have smth troubles with compiling app for linux & haxe 3.2.1/hxcpp
here is short discussion of this theme http://stackoverflow.com/questions/33577290/haxeui-projects-wont-compile-for-windows-error-c2259-cannot-instantiate-abs

here is my compilation log: http://pastebin.com/qmN1gVt3
my *.hxml file http://pastebin.com/w2uHVfdT and *.xml http://pastebin.com/Tp7VQ8au
and source of main class http://pastebin.com/GS4TMWrz

Linux Mint 14.2 x64

$ haxe
Haxe Compiler 3.2.1 - (C)2005-2015 Haxe Foundation
$ neko
NekoVM 2.0.0 (c)2005-2013 Haxe Foundation
$ haxelib list
actuate: [1.8.6]
flow: git [dev:/usr/share/haxelib/flow/git]
format: [3.2.1]
haxeui: 1.8.0 [1.8.2] 1.8.1
HaxeUmlGen: [0.2.1]
hscript: [2.0.5]
hxcpp: [3.2.193] 3.2.94 3.2.102
hxcs: [3.2.0]
ihx: [0.3.4]
lime-samples: [2.6.0]
lime-tools: [1.5.7]
lime: [2.8.1] 2.7.0
openfl-html5: [1.0.5]
openfl-native: [1.4.0]
openfl-nativedialog: [1.2.0]
openfl-samples: [3.3.1]
openfl: [3.5.1] 3.4.0
snow: git [dev:/usr/share/haxelib/snow/git]

maybe somebody know solution how to compile haxeui application with haxe 3.2.1+hxcpp? thanks

**Comment by ianharrigan** [comment]
Can you try with the latest version of haxeui `1.8.5` - it should be fixed there now.

**Comment by r3d9u11** [comment]
how it works fine, thank you!
