### ISSUE TITLE
The images does not allow more than one event listener

### ISSUE THREAD

**Issue by patrixd** [ianharrigan/haxeui#328]
Hi
I'm trying to listen more than one event to an image and only works the first handler of the events listened. What I have to do to make it works?

````
        function new(){
                this.addEventListener(UIEvent.CLICK, onClickButton);
        }
```` 
If I listen the object outside:

````
        myImage.addEventListener(UIEvent.CLICK, onClickButton2);
```` 
onClickButton2 does not work. It should be called fist onClickButton and after onClickButton2.
In onClickButton I'm not doing anything that induce this behaivour.
Thanks a lot.

**Comment by ianharrigan** [comment]
This works fine for me:

```haxe
class TestImage extends Image {
	public function new() {
		super();
		
		this.addEventListener(UIEvent.CLICK, onClickButton);
	}
	
	private function onClickButton(event:UIEvent) {
		trace("TestImage::onClickButton");
	}
}
```

and

```haxe
		Toolkit.open(function(root:Root) {
			var t:TestImage = new TestImage();
			t.resource = "assets/haxeui.png";
			t.addEventListener(UIEvent.CLICK, function(e:UIEvent) {
				trace("another click");
			});
			root.addChild(t);
		});
```

**Comment by aW4KeNiNG** [comment]
I think that @patrixd would have the same problem with #332 . I hope that she can confirm that the last commit works in her code.

**Comment by patrixd** [comment]
Yes @aW4KeNiNG now it works. Thank you so much.

**Comment by ianharrigan** [comment]
Sorry, totally forgot about this... thank @aW4KeNiNG! 

@patrixd - can you close this if you feel its fixed when you get a moment?

Cheers guys!
