### ISSUE TITLE
Compilation Error with hxcpp 3.2.205 to cpp and java.

### ISSUE THREAD

**Issue by NoTalentGeek** [ianharrigan/haxeui#330]
Error: ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp: In member function ‘haxe::ui::toolkit::core::renderers::ItemRenderer_obj::operator haxe::ui::toolkit::core::interfaces::IStyleableDisplayObject_obj*()’:
    ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:161:112: error: invalid new-expression of abstract class type ‘haxe::ui::toolkit::core::interfaces::IStyleableDisplayObject_delegate_<haxe::ui::toolkit::core::renderers::ItemRenderer_obj>’
      { return new ::haxe::ui::toolkit::core::interfaces::IStyleableDisplayObject_delegate_< ItemRenderer_obj >(this); }
                                                                                                                    ^
    In file included from include/haxe/ui/toolkit/core/StyleableDisplayObject.h:15:0,
                     from include/haxe/ui/toolkit/core/Component.h:9,
                     from include/haxe/ui/toolkit/core/StateComponent.h:9,
                     from include/haxe/ui/toolkit/controls/Button.h:9,
                     from ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:10:
    include/haxe/ui/toolkit/core/interfaces/IStyleableDisplayObject.h:58:7: note:   because the following virtual functions are pure within ‘haxe::ui::toolkit::core::interfaces::IStyleableDisplayObject_delegate_<haxe::ui::toolkit::core::renderers::ItemRenderer_obj>’:
     class IStyleableDisplayObject_delegate_ : public IStyleableDisplayObject_obj
           ^
    In file included from include/haxe/ui/toolkit/core/DisplayObject.h:15:0,
                     from include/haxe/ui/toolkit/core/DisplayObjectContainer.h:9,
                     from include/haxe/ui/toolkit/core/StyleableDisplayObject.h:9,
                     from include/haxe/ui/toolkit/core/Component.h:9,
                     from include/haxe/ui/toolkit/core/StateComponent.h:9,
                     from include/haxe/ui/toolkit/controls/Button.h:9,
                     from ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:10:
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:127:16: note:  virtual Void haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::addEventListener(String, Dynamic, hx::Null<bool>, hx::Null<int>, hx::Null<bool>)
       virtual Void addEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture,hx::Null< int >  priority,hx::Null< bool >  useWeakReference)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:128:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::addEventListener_dyn()
     virtual Dynamic addEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:129:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::dispatchEvent(openfl::_legacy::events::Event)
       virtual bool dispatchEvent( ::openfl::_legacy::events::Event event)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:130:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::dispatchEvent_dyn()
     virtual Dynamic dispatchEvent_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:131:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::hasEventListener(String)
       virtual bool hasEventListener( ::String type)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:132:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::hasEventListener_dyn()
     virtual Dynamic hasEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:133:16: note:  virtual Void haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::removeEventListener(String, Dynamic, hx::Null<bool>)
       virtual Void removeEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:134:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::removeEventListener_dyn()
     virtual Dynamic removeEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:135:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::willTrigger(String)
       virtual bool willTrigger( ::String type)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:136:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::willTrigger_dyn()
     virtual Dynamic willTrigger_dyn()=0;
                     ^
    ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp: In member function ‘haxe::ui::toolkit::core::renderers::ItemRenderer_obj::operator haxe::ui::toolkit::core::interfaces::IComponent_obj*()’:
    ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:165:99: error: invalid new-expression of abstract class type ‘haxe::ui::toolkit::core::interfaces::IComponent_delegate_<haxe::ui::toolkit::core::renderers::ItemRenderer_obj>’
      { return new ::haxe::ui::toolkit::core::interfaces::IComponent_delegate_< ItemRenderer_obj >(this); }
                                                                                                       ^
    In file included from include/haxe/ui/toolkit/core/Component.h:15:0,
                     from include/haxe/ui/toolkit/core/StateComponent.h:9,
                     from include/haxe/ui/toolkit/controls/Button.h:9,
                     from ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:10:
    include/haxe/ui/toolkit/core/interfaces/IComponent.h:56:7: note:   because the following virtual functions are pure within ‘haxe::ui::toolkit::core::interfaces::IComponent_delegate_<haxe::ui::toolkit::core::renderers::ItemRenderer_obj>’:
     class IComponent_delegate_ : public IComponent_obj
           ^
    In file included from include/haxe/ui/toolkit/core/DisplayObject.h:15:0,
                     from include/haxe/ui/toolkit/core/DisplayObjectContainer.h:9,
                     from include/haxe/ui/toolkit/core/StyleableDisplayObject.h:9,
                     from include/haxe/ui/toolkit/core/Component.h:9,
                     from include/haxe/ui/toolkit/core/StateComponent.h:9,
                     from include/haxe/ui/toolkit/controls/Button.h:9,
                     from ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:10:
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:127:16: note:  virtual Void haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::addEventListener(String, Dynamic, hx::Null<bool>, hx::Null<int>, hx::Null<bool>)
       virtual Void addEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture,hx::Null< int >  priority,hx::Null< bool >  useWeakReference)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:128:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::addEventListener_dyn()
     virtual Dynamic addEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:129:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::dispatchEvent(openfl::_legacy::events::Event)
       virtual bool dispatchEvent( ::openfl::_legacy::events::Event event)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:130:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::dispatchEvent_dyn()
     virtual Dynamic dispatchEvent_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:131:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::hasEventListener(String)
       virtual bool hasEventListener( ::String type)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:132:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::hasEventListener_dyn()
     virtual Dynamic hasEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:133:16: note:  virtual Void haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::removeEventListener(String, Dynamic, hx::Null<bool>)
       virtual Void removeEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:134:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::removeEventListener_dyn()
     virtual Dynamic removeEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:135:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::willTrigger(String)
       virtual bool willTrigger( ::String type)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:136:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::willTrigger_dyn()
     virtual Dynamic willTrigger_dyn()=0;
                     ^
    ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp: In member function ‘haxe::ui::toolkit::core::renderers::ItemRenderer_obj::operator haxe::ui::toolkit::core::interfaces::IStateComponent_obj*()’:
    ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:171:104: error: invalid new-expression of abstract class type ‘haxe::ui::toolkit::core::interfaces::IStateComponent_delegate_<haxe::ui::toolkit::core::renderers::ItemRenderer_obj>’
      { return new ::haxe::ui::toolkit::core::interfaces::IStateComponent_delegate_< ItemRenderer_obj >(this); }
                                                                                                            ^
    In file included from include/haxe/ui/toolkit/core/StateComponent.h:15:0,
                     from include/haxe/ui/toolkit/controls/Button.h:9,
                     from ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:10:
    include/haxe/ui/toolkit/core/interfaces/IStateComponent.h:43:7: note:   because the following virtual functions are pure within ‘haxe::ui::toolkit::core::interfaces::IStateComponent_delegate_<haxe::ui::toolkit::core::renderers::ItemRenderer_obj>’:
     class IStateComponent_delegate_ : public IStateComponent_obj
           ^
    In file included from include/haxe/ui/toolkit/core/DisplayObject.h:15:0,
                     from include/haxe/ui/toolkit/core/DisplayObjectContainer.h:9,
                     from include/haxe/ui/toolkit/core/StyleableDisplayObject.h:9,
                     from include/haxe/ui/toolkit/core/Component.h:9,
                     from include/haxe/ui/toolkit/core/StateComponent.h:9,
                     from include/haxe/ui/toolkit/controls/Button.h:9,
                     from ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:10:
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:127:16: note:  virtual Void haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::addEventListener(String, Dynamic, hx::Null<bool>, hx::Null<int>, hx::Null<bool>)
       virtual Void addEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture,hx::Null< int >  priority,hx::Null< bool >  useWeakReference)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:128:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::addEventListener_dyn()
     virtual Dynamic addEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:129:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::dispatchEvent(openfl::_legacy::events::Event)
       virtual bool dispatchEvent( ::openfl::_legacy::events::Event event)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:130:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::dispatchEvent_dyn()
     virtual Dynamic dispatchEvent_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:131:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::hasEventListener(String)
       virtual bool hasEventListener( ::String type)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:132:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::hasEventListener_dyn()
     virtual Dynamic hasEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:133:16: note:  virtual Void haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::removeEventListener(String, Dynamic, hx::Null<bool>)
       virtual Void removeEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:134:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::removeEventListener_dyn()
     virtual Dynamic removeEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:135:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::willTrigger(String)
       virtual bool willTrigger( ::String type)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:136:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::willTrigger_dyn()
     virtual Dynamic willTrigger_dyn()=0;
                     ^
    ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp: In member function ‘haxe::ui::toolkit::core::renderers::ItemRenderer_obj::operator haxe::ui::toolkit::core::interfaces::IDisplayObjectContainer_obj*()’:
    ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:173:112: error: invalid new-expression of abstract class type ‘haxe::ui::toolkit::core::interfaces::IDisplayObjectContainer_delegate_<haxe::ui::toolkit::core::renderers::ItemRenderer_obj>’
      { return new ::haxe::ui::toolkit::core::interfaces::IDisplayObjectContainer_delegate_< ItemRenderer_obj >(this); }
                                                                                                                    ^
    In file included from include/haxe/ui/toolkit/core/DisplayObjectContainer.h:15:0,
                     from include/haxe/ui/toolkit/core/StyleableDisplayObject.h:9,
                     from include/haxe/ui/toolkit/core/Component.h:9,
                     from include/haxe/ui/toolkit/core/StateComponent.h:9,
                     from include/haxe/ui/toolkit/controls/Button.h:9,
                     from ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:10:
    include/haxe/ui/toolkit/core/interfaces/IDisplayObjectContainer.h:67:7: note:   because the following virtual functions are pure within ‘haxe::ui::toolkit::core::interfaces::IDisplayObjectContainer_delegate_<haxe::ui::toolkit::core::renderers::ItemRenderer_obj>’:
     class IDisplayObjectContainer_delegate_ : public IDisplayObjectContainer_obj
           ^
    In file included from include/haxe/ui/toolkit/core/DisplayObject.h:15:0,
                     from include/haxe/ui/toolkit/core/DisplayObjectContainer.h:9,
                     from include/haxe/ui/toolkit/core/StyleableDisplayObject.h:9,
                     from include/haxe/ui/toolkit/core/Component.h:9,
                     from include/haxe/ui/toolkit/core/StateComponent.h:9,
                     from include/haxe/ui/toolkit/controls/Button.h:9,
                     from ./src/haxe/ui/toolkit/core/renderers/ItemRenderer.cpp:10:
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:127:16: note:  virtual Void haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::addEventListener(String, Dynamic, hx::Null<bool>, hx::Null<int>, hx::Null<bool>)
       virtual Void addEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture,hx::Null< int >  priority,hx::Null< bool >  useWeakReference)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:128:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::addEventListener_dyn()
     virtual Dynamic addEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:129:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::dispatchEvent(openfl::_legacy::events::Event)
       virtual bool dispatchEvent( ::openfl::_legacy::events::Event event)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:130:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::dispatchEvent_dyn()
     virtual Dynamic dispatchEvent_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:131:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::hasEventListener(String)
       virtual bool hasEventListener( ::String type)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:132:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::hasEventListener_dyn()
     virtual Dynamic hasEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:133:16: note:  virtual Void haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::removeEventListener(String, Dynamic, hx::Null<bool>)
       virtual Void removeEventListener( ::String type,Dynamic listener,hx::Null< bool >  useCapture)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:134:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::removeEventListener_dyn()
     virtual Dynamic removeEventListener_dyn()=0;
                     ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:135:16: note:  virtual bool haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::willTrigger(String)
       virtual bool willTrigger( ::String type)=0;
                    ^
    include/haxe/ui/toolkit/core/interfaces/IDisplayObject.h:136:17: note:  virtual Dynamic haxe::ui::toolkit::core::interfaces::IDisplayObject_obj::willTrigger_dyn()
     virtual Dynamic willTrigger_dyn()=0;

**Comment by ianharrigan** [comment]
Is this on a mac? I think this is a bug in hxcpp that hasnt yet been resolved? It sounds like its related to: https://github.com/ianharrigan/haxeui/issues/326 or https://github.com/ianharrigan/haxeui/issues/282?

**Comment by NoTalentGeek** [comment]
Hey I am using UbuntuMate 64-bit. This is a bit weird for me because I remember like ~2 weeks ago I can successfully compile haxeui in all target.

Right now I am trying to downgrade the hxcpp from 3.2.205 to 3.2.193.

**Comment by NoTalentGeek** [comment]
Hey Ian, I tried to downgrade the hxcpp but no change. However, Haxe 3.2.0 do the tricks.

**Comment by ianharrigan** [comment]
Can you try with the latest version of haxeui `1.8.5` - it should be fixed there now.

**Comment by NoTalentGeek** [comment]
Hey Ian sorry I just see this. At the moment I am using 1.8.6, HaXe 3.2.1 and hxcpp 3.2.205 it is all works fine.

No need to use HaXe 3.2.0 anymore.
