### ISSUE TITLE
PopupManager.instance.hidePopup(); does not working as intended in Flash target.

### ISSUE THREAD

**Issue by NoTalentGeek** [ianharrigan/haxeui#339]
Check my example here.
https://notalentgeek.itch.io/e-haxeopenflmuseummanager

The translucent overlay display is still in the screen when the popup is gone. Here is the screenshot.
![selection_002](https://cloud.githubusercontent.com/assets/881506/13176131/005e035c-d710-11e5-9fc3-40e38377b30f.png)

**Comment by ianharrigan** [comment]
Hmmm... Strange. Do you have a minimal example that i can test

**Comment by NoTalentGeek** [comment]
Well I have a repository.
[https://github.com/NoTalentGeek/HaXeOpenFLMuseumManager](https://github.com/NoTalentGeek/HaXeOpenFLMuseumManager)

However, I used the forked version of your haxeui library.
[https://github.com/NoTalentGeek/haxeui](https://github.com/NoTalentGeek/haxeui)

And these libraries:

- actuate
- haxeui
- haxeui-rich-text
- hxSerial
- openfl

**Comment by ianharrigan** [comment]
Right, but i dont have time to wade through a large, working project looking for bugs to be honest. I would suggest you create a smaller / simpler project that does the same thing there (ie, a minimal example) and see if the problem persists there. If it does then i can probably help with that minimised scope. 

Cheers,
Ian

**Comment by NoTalentGeek** [comment]
Yeah no problem. It is quite big.

**Comment by NoTalentGeek** [comment]
[https://www.dropbox.com/s/y0fq6qake2en4wv/HaXeOpenFLTestPopup.zip?dl=0](https://www.dropbox.com/s/y0fq6qake2en4wv/HaXeOpenFLTestPopup.zip?dl=0) With Linux and Flash export.
[https://www.dropbox.com/s/ud2xoju20sf9tiv/HaXeOpenFLTestPopupNoExport.zip?dl=0](https://www.dropbox.com/s/ud2xoju20sf9tiv/HaXeOpenFLTestPopupNoExport.zip?dl=0) Just the code.

It is the simplest code to hide and show a popup object. My problem is still present.

**Comment by ianharrigan** [comment]
Ok, thats much easier to work with ;). It seems a little strange to be removing a popup in an update look, but regardless, i wouldnt expect it to error. The error is that you are trying to remove the popup from a root and that popup display object isnt a child of the root (yet i presume). 

Im going to tighten up removeChild calls to first make sure its actually a child. Give me 5 mins.

**Comment by ianharrigan** [comment]
Ok, should be fixed now in haxelib v1.8.17

**Comment by NoTalentGeek** [comment]
Hey it is perfect! Thank you so much Ian :)))).
