### ISSUE TITLE
how to debug in Haxe?

### ISSUE THREAD

**Issue by aammfe** [ianharrigan/haxeui#362]
Hi!

i m new to haxe, using Haxedevelop ,
i have came from flashbuilder , where debugging is very very easy .

but here things are upside down, i m using haxe for html5.
no break points , no run time error , no sign of debugging.

if error occur screen just go blank.

i have googled this thing and got no satisfaction.
u have developed whole framework , 

1-how you do things ,like debugging, and other stuff
2-what IDE you are using ,.. 
3-what are your best practices..
4- is there any forum dedicated for your stuff.

**Comment by hoseyjoe** [comment]
This link should help
http://www.openfl.org/archive/community/programming-haxe/how-do-you-debuglogging-in-html5-target/

**Comment by ianharrigan** [comment]
Agreed, closing this as its not HaxeUI related per se.
