### ISSUE TITLE
Not import haxe.ui.toolkit.controls.Button 

### ISSUE THREAD

**Issue by tuanntjvb** [ianharrigan/haxeui#372]
I have a problem when building haxe
Type not found: haxe.ui.toolkit.controls.Button.
haxelib list
actuate: [1.8.9]
box2d: [1.2.3]
haxeui-core: [0.0.4] git
haxeui-openfl: [git]
haxeui: [1.8.21]
hscript: [2.3.0]
hxcpp: [4.0.4]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: 2.9.1 [7.2.0]
openfl-samples: [8.4.0]
openfl: 3.6.1 [8.7.0]
perf.js: [1.1.8]
pixijs: [4.7.1]
pls help me!

**Comment by ianharrigan** [comment]
any more info? Got a project? How are you building?

Cheers,
Ian

**Comment by tuanntjvb** [comment]
Tks sir, I solved the problem!
