### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by ianharrigan** [ianharrigan/haxeui#53]
Need some type of customizable tooltip system.

**Comment by marcelofrau** [comment]
Just another suggestion is some kind of control the show and hide tooltip by code. 
E.g. 
{code}
button = new Button();
button.tooltipText = "Tooltip Text";
button.tooltipWindow.show();
button.tooltipWindow.hide();
{code}

Not exaclty in this way, but if you can provide such functionality the tooltips can be used in other forms aside only desktop applications. 

Android and all touch devices does not have the over functionality in the most of devices, so the tooltip was never going to be displayed/used on these devices.

If you provide the functionality to show/hide by error you can add another button like a help button (?) that toggles the tooltip visibility.

What do you think?

**Comment by ianharrigan** [comment]
Yeah, this will be part of the functionality (and actually already exists in the implementation i have hlaf working now)... This is my checklist:

* Based on IItemRenderer, so these should work:
```xml
  <button toolTip="hello" />
  <button toolTop="hello" toolTipRenderer="haxe.ui.tooltips.DefaultRenderer" />
  <button toolTip="hello">
    <toolTipRenderer>
      <text id="text" />
    </toolTip>
  </button>
```

* Manager based
  - Things like "ToolTipManager.showTooltip(component, options)" should be possible
  - Manager should have default props, but components can override them
  - Singletons, only one tooltip allowed at a time

* Properties
  - position: top, left, bottom right
  - relativeTo: cursor, component
  - center: true/false - if the tool should be centered agaist cursor/component
  - offset: x, y
  - delay: 1000
  - follow (cursor): true/false - If it should follow the cursor until mouse out, other wise mouse move hides it. Only relavant for relativeTo=cursor

And although not fully functional, so far it looks like this:
![tooltips](https://cloud.githubusercontent.com/assets/3024242/6091604/b4f80234-aeb4-11e4-82b4-fd7ad0468a6e.png)

**Comment by marcelofrau** [comment]
Looks good! Can't wait to see :)

**Comment by ianharrigan** [comment]
This is done now, however, for now, i havent allowed custom renderers. That is, you can only have text based tooltips. I decided to go down this route as its plainly just simpler. And, although possible to add item renderers so you can have lists, icons, anything in tooltips i think its overkill. 

I mean, i would imagine that "general" use would be text based, so didnt really see the need in complicating the sub system to allow for fringe cases that would never be used. Plus, there are other things that i think need attention first. Im going to close this log and if use cases come up ill treat them as seperate issues. 

Ian

PS: demo here: https://dl.dropboxusercontent.com/u/26678671/haxeuitooltips.swf
